#!/bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width          2
bspc config window_gap            6

bspc config split_ratio           0.50
bspc config borderless_monocle    true
bspc config gapless_monocle       true

bspc config focused_border_color "#ebdbb2"
bspc config normal_border_color  "#282828"

bspc config focus_follows_pointer      true
bspc config pointer_follows_monitor    true

bspc rule -a mpv state=floating center=on

# Autoruns
~/.config/polybar/start.sh &
feh --bg-fill --no-fehbg --randomize ~/pictures/wallpapers/* &
picom &
xsetroot -cursor_name left_ptr &
